name: build-test
run-name: build and test
on: [ push ]
jobs:
    build-on-push:
      runs-on: ubuntu-latest
      
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build and run Docker image
        run: |
          docker build -t hello .
          docker run -d --name hello -p 80:80 hello
          sleep 5  # Give the container some time to start
      
      - name: Test the application
        run: curl http://localhost |sleep 40
        # | grep 'Hello, World!'
      
      - name: Stop the container
        run: docker stop hello