name: build-test
run-name: build and test
on: [ push ]
jobs:
    build-on-push:
      runs-on: ubuntu-latest
      
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build and run Docker image
        run: |
          docker build -t hello .
          docker run -d --name hello -p 3000:3000 hello
          sleep 5  # Give the container some time to start
      
      - name: Test the application
        run: |
          output=$(curl -s http://localhost:3000)
          if [[ "$output" == "Hello, World!" ]]; then
            echo "HTML worked"
          else
            echo "Error with web"
            exit 1
          fi
    