name: conditionWF
run-name: is test changed

on:
  push:
    paths:
      - 'test.txt'

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print warning
      run: echo "Pay Attention test.txt has been modified."
