name: conditionWF
run-name: is test changed

on:
  push:
    paths:
      - 'test.txt'

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print warning
      run: echo "Pay Attention test.txt has been modified."

    - name: Append date to test.txt
      run: echo "Updated on $(date)" >> test.txt

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add test.txt
        git commit -m "Append date to test.txt"
        git push
